namespace DarouichTravaux.Domain;

public abstract class Entity { public Guid Id { get; set; } = Guid.NewGuid(); public DateTime CreatedAtUtc { get; set; } = DateTime.UtcNow; }
public sealed class Client : Entity { public required string Name { get; set; } public string? CompanyName { get; set; } public string? Phone { get; set; } public string? Email { get; set; } public string? Address { get; set; } public string? City { get; set; } public string? Ice { get; set; } public string? TaxId { get; set; } public string? Rc { get; set; } public string? Cnie { get; set; } public string? Notes { get; set; } public ICollection<Project> Projects { get; } = []; }
public enum ProjectStatus { Draft, Planned, Active, Paused, Completed, Cancelled }
public sealed class Project : Entity { public required string Code { get; set; } public required string Name { get; set; } public Guid ClientId { get; set; } public Client Client { get; set; } = null!; public string? Address { get; set; } public string? City { get; set; } public string? Description { get; set; } public DateOnly StartDate { get; set; } public DateOnly? ExpectedEndDate { get; set; } public DateOnly? ActualEndDate { get; set; } public decimal ContractAmount { get; set; } public decimal Budget { get; set; } public decimal Progress { get; set; } public string? Manager { get; set; } public ProjectStatus Status { get; set; } }
public enum DocumentStatus { Draft, Sent, Accepted, Rejected, Expired, PartiallyPaid, Paid, Overdue, Cancelled }
public abstract class SalesDocument : Entity { public required string Number { get; set; } public Guid ClientId { get; set; } public Client Client { get; set; } = null!; public Guid? ProjectId { get; set; } public Project? Project { get; set; } public DateOnly Date { get; set; } public DocumentStatus Status { get; set; } public string? Notes { get; set; } public decimal TotalExcludingTax { get; set; } public decimal TaxTotal { get; set; } public decimal TotalIncludingTax { get; set; } }
public sealed class Quote : SalesDocument { public DateOnly ValidUntil { get; set; } public string? Terms { get; set; } public ICollection<QuoteItem> Items { get; } = []; }
public sealed class QuoteItem : Entity { public Guid QuoteId { get; set; } public Quote Quote { get; set; } = null!; public required string Designation { get; set; } public string? Description { get; set; } public decimal Quantity { get; set; } public required string Unit { get; set; } public decimal UnitPrice { get; set; } public decimal TaxRate { get; set; } }
public sealed class Invoice : SalesDocument { public DateOnly DueDate { get; set; } public string? PaymentMethod { get; set; } public decimal PaidAmount { get; set; } public decimal Balance => TotalIncludingTax - PaidAmount; public ICollection<InvoiceItem> Items { get; } = []; public ICollection<Payment> Payments { get; } = []; }
public sealed class InvoiceItem : Entity { public Guid InvoiceId { get; set; } public Invoice Invoice { get; set; } = null!; public required string Designation { get; set; } public string? Description { get; set; } public decimal Quantity { get; set; } public required string Unit { get; set; } public decimal UnitPrice { get; set; } public decimal TaxRate { get; set; } }
public sealed class Payment : Entity { public Guid InvoiceId { get; set; } public Invoice Invoice { get; set; } = null!; public DateOnly Date { get; set; } public decimal Amount { get; set; } public required string Method { get; set; } public string? Reference { get; set; } public string? Notes { get; set; } }
public sealed class Expense : Entity { public Guid? ProjectId { get; set; } public Project? Project { get; set; } public DateOnly Date { get; set; } public required string Description { get; set; } public required string Category { get; set; } public decimal AmountExcludingTax { get; set; } public decimal TaxRate { get; set; } public decimal AmountIncludingTax { get; set; } public string? ReceiptPath { get; set; } }
public sealed class CompanySettings : Entity { public string Name { get; set; } = "Darouich Travaux"; public string? Address { get; set; } public string? Phone { get; set; } public string? Email { get; set; } public string? Ice { get; set; } public string? TaxId { get; set; } public string? Rc { get; set; } public string? BankDetails { get; set; } }
