using System.Text.RegularExpressions;
using DarouichTravaux.Application;
using DarouichTravaux.Domain;
using DarouichTravaux.Infrastructure.Database;

namespace DarouichTravaux.Infrastructure.Services;

public sealed class ClientService(SqliteDatabase database) : IClientService
{
    public async Task<IReadOnlyList<Client>> SearchAsync(string? query, CancellationToken cancellationToken = default)
    {
        var rows = new List<Client>(); await using var connection = database.OpenConnection(); await using var command = connection.CreateCommand();
        command.CommandText = "SELECT Id,Name,CompanyName,Phone,Email,Address,City,Ice,TaxId,Rc,Cnie,Notes,CreatedAtUtc,UpdatedAtUtc FROM Clients WHERE $query='' OR Name LIKE '%'||$query||'%' COLLATE NOCASE ORDER BY Name"; command.Parameters.AddWithValue("$query", query?.Trim() ?? "");
        await using var reader = await command.ExecuteReaderAsync(cancellationToken); while (await reader.ReadAsync(cancellationToken)) rows.Add(new Client { Id=Guid.Parse(reader.GetString(0)), Name=reader.GetString(1), CompanyName=reader.IsDBNull(2)?null:reader.GetString(2), Phone=reader.IsDBNull(3)?null:reader.GetString(3), Email=reader.IsDBNull(4)?null:reader.GetString(4), Address=reader.IsDBNull(5)?null:reader.GetString(5), City=reader.IsDBNull(6)?null:reader.GetString(6), Ice=reader.IsDBNull(7)?null:reader.GetString(7), TaxId=reader.IsDBNull(8)?null:reader.GetString(8), Rc=reader.IsDBNull(9)?null:reader.GetString(9), Cnie=reader.IsDBNull(10)?null:reader.GetString(10), Notes=reader.IsDBNull(11)?null:reader.GetString(11), CreatedAtUtc=DateTime.Parse(reader.GetString(12)), UpdatedAtUtc=DateTime.Parse(reader.GetString(13)) }); return rows;
    }
    public async Task SaveAsync(Client client, CancellationToken cancellationToken = default) { if(string.IsNullOrWhiteSpace(client.Name))throw new ArgumentException("Le nom est obligatoire."); client.UpdatedAtUtc=DateTime.UtcNow; await using var connection=database.OpenConnection(); await using var command=connection.CreateCommand(); command.CommandText="INSERT INTO Clients VALUES($id,$name,$company,$phone,$email,$address,$city,$ice,$tax,$rc,$cnie,$notes,$created,$updated) ON CONFLICT(Id) DO UPDATE SET Name=$name,CompanyName=$company,Phone=$phone,Email=$email,Address=$address,City=$city,Ice=$ice,TaxId=$tax,Rc=$rc,Cnie=$cnie,Notes=$notes,UpdatedAtUtc=$updated"; command.Parameters.AddWithValue("$id",client.Id.ToString());command.Parameters.AddWithValue("$name",client.Name.Trim());command.Parameters.AddWithValue("$company",(object?)client.CompanyName??DBNull.Value);command.Parameters.AddWithValue("$phone",(object?)client.Phone??DBNull.Value);command.Parameters.AddWithValue("$email",(object?)client.Email??DBNull.Value);command.Parameters.AddWithValue("$address",(object?)client.Address??DBNull.Value);command.Parameters.AddWithValue("$city",(object?)client.City??DBNull.Value);command.Parameters.AddWithValue("$ice",(object?)client.Ice??DBNull.Value);command.Parameters.AddWithValue("$tax",(object?)client.TaxId??DBNull.Value);command.Parameters.AddWithValue("$rc",(object?)client.Rc??DBNull.Value);command.Parameters.AddWithValue("$cnie",(object?)client.Cnie??DBNull.Value);command.Parameters.AddWithValue("$notes",(object?)client.Notes??DBNull.Value);command.Parameters.AddWithValue("$created",client.CreatedAtUtc.ToString("O"));command.Parameters.AddWithValue("$updated",client.UpdatedAtUtc.ToString("O"));await command.ExecuteNonQueryAsync(cancellationToken); }
    public async Task DeleteAsync(Guid id,CancellationToken cancellationToken=default){await using var connection=database.OpenConnection();await using var command=connection.CreateCommand();command.CommandText="DELETE FROM Clients WHERE Id=$id";command.Parameters.AddWithValue("$id",id.ToString());await command.ExecuteNonQueryAsync(cancellationToken);}
}

public sealed class DashboardService(SqliteDatabase database):IDashboardService { public async Task<DashboardDto> GetAsync(CancellationToken ct=default){await using var c=database.OpenConnection();async Task<decimal> Sum(string sql){await using var cmd=c.CreateCommand();cmd.CommandText=sql;return Convert.ToDecimal(await cmd.ExecuteScalarAsync(ct));}async Task<int> Count(string sql){await using var cmd=c.CreateCommand();cmd.CommandText=sql;return Convert.ToInt32(await cmd.ExecuteScalarAsync(ct));}var invoiced=await Sum("SELECT COALESCE(SUM(TotalIncludingTax),0) FROM Invoices WHERE Status<>5");var paid=await Sum("SELECT COALESCE(SUM(PaidAmount),0) FROM Invoices");var expenses=await Sum("SELECT COALESCE(SUM(AmountIncludingTax),0) FROM Expenses");return new(invoiced,paid,invoiced-paid,expenses,paid-expenses,await Count("SELECT COUNT(*) FROM Projects WHERE Status=2"),await Count("SELECT COUNT(*) FROM Invoices WHERE Status=4"));} }

public sealed partial class InvoiceFileNameService:IInvoiceFileNameService { [GeneratedRegex("[^a-zA-Z0-9À-ÿ_-]")]private static partial Regex Invalid();[GeneratedRegex("_+")]private static partial Regex Repeated();public string BuildInvoiceFileName(Invoice invoice){var client=Repeated().Replace(Invalid().Replace(invoice.ClientName.Trim().Replace(' ','_'),""),"_").Trim('_');var number=Invalid().Replace(invoice.Number,"");return $"Facture({client})-{number}.pdf";} }
