using System.Text.RegularExpressions;
using DarouichTravaux.Application;
using DarouichTravaux.Domain;
using Microsoft.EntityFrameworkCore;
namespace DarouichTravaux.Infrastructure;
public sealed class ClientService(AppDbContext db) : IClientService { public async Task<IReadOnlyList<Client>> SearchAsync(string? q, CancellationToken ct = default) => await db.Clients.Where(x => string.IsNullOrWhiteSpace(q) || EF.Functions.ILike(x.Name, $"%{q}%")).OrderBy(x => x.Name).ToListAsync(ct); public async Task<Client> SaveAsync(Client client, CancellationToken ct = default) { if (string.IsNullOrWhiteSpace(client.Name)) throw new ArgumentException("Le nom est obligatoire."); db.Update(client); await db.SaveChangesAsync(ct); return client; } }
public sealed class ProjectService(AppDbContext db) : IProjectService { public async Task<IReadOnlyList<Project>> ListAsync(CancellationToken ct = default) => await db.Projects.Include(x => x.Client).OrderByDescending(x => x.CreatedAtUtc).ToListAsync(ct); }
public sealed class DashboardService(AppDbContext db) : IDashboardService { public async Task<DashboardDto> GetAsync(CancellationToken ct = default) { var invoiced = await db.Invoices.Where(x => x.Status != DocumentStatus.Cancelled).SumAsync(x => x.TotalIncludingTax, ct); var paid = await db.Payments.SumAsync(x => x.Amount, ct); var expenses = await db.Expenses.SumAsync(x => x.AmountIncludingTax, ct); return new(invoiced, paid, invoiced-paid, expenses, paid-expenses, await db.Projects.CountAsync(x => x.Status == ProjectStatus.Active, ct), await db.Invoices.CountAsync(x => x.Status == DocumentStatus.Overdue, ct)); } }
public static partial class InvoiceFileNames { [GeneratedRegex("[^a-zA-Z0-9À-ÿ_-]")] private static partial Regex Invalid(); [GeneratedRegex("_+")] private static partial Regex Underscores(); public static string Build(Invoice invoice) { var client = invoice.Client?.Name ?? "Client"; var clean = Underscores().Replace(Invalid().Replace(client.Trim().Replace(' ', '_'), ""), "_").Trim('_'); var number = Invalid().Replace(invoice.Number, ""); return $"Facture({clean})-{number}.pdf"; } }
